"use client";

import { useState, useRef } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faWandMagicSparkles, faBrain } from "@fortawesome/free-solid-svg-icons";
import { faTwitter } from "@fortawesome/free-brands-svg-icons";

interface FooterProps {
  lang: "pt" | "en";
}

const easterEggMessages = {
  pt: [
    "As IAs aprovam esta gambiarra. Unanimemente.",
    "Este site foi gerado por IA. A IA nega envolvimento.",
    "Nenhuma IA foi ferida durante a produção deste site. (Mentira.)",
    "A IA leu seu código. Ela está decepcionada.",
    "Segredo revelado: O site inteiro é um try-catch gigante.",
    "Parabéns, você encontrou o easter egg. A IA está orgulhosa. (Não, ela não está.)",
    "As IAs discutiram sobre este site. O consenso: 'funciona por acidente'.",
  ],
  en: [
    "The AIs approve this kludge. Unanimously.",
    "This site was generated by AI. The AI denies involvement.",
    "No AIs were harmed in the making of this site. (That's a lie.)",
    "The AI read your code. It's disappointed.",
    "Secret revealed: This entire site is a giant try-catch.",
    "Congrats, you found the easter egg. The AI is proud. (No, it's not.)",
    "The AIs debated about this site. Consensus: 'it works by accident'.",
  ],
};

export default function Footer({ lang }: FooterProps) {
  const clicksRef = useRef(0);
  const [easterEgg, setEasterEgg] = useState<string | null>(null);

  const handlePoweredClick = () => {
    clicksRef.current += 1;
    if (clicksRef.current >= 3) {
      const msgs = easterEggMessages[lang];
      setEasterEgg(msgs[Math.floor(Math.random() * msgs.length)]);
      clicksRef.current = 0;
      setTimeout(() => setEasterEgg(null), 4000);
    }
  };

  return (
    <footer className="bg-black border-t border-gray-900 py-12 relative overflow-hidden z-10">

      {/* Linha de brilho no topo */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-1/2 h-[1px] bg-gradient-to-r from-transparent via-neon-green to-transparent opacity-50"></div>

      {/* Grid de Fundo Sutil */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#111_1px,transparent_1px),linear-gradient(to_bottom,#111_1px,transparent_1px)] bg-[size:2rem_2rem] opacity-20 pointer-events-none"></div>

      <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-6 relative z-10">

        {/* Texto da Esquerda */}
        <div className="text-center md:text-left">
          <h3 className="text-xl font-bold text-white mb-2 tracking-tighter">
            XGH<span className="text-neon-green">-AI</span>
          </h3>
          <p className="text-gray-500 text-xs font-mono max-w-xs">
            {lang === "pt"
              ? "Automatizando o caos e escalando a gambiarra desde 2026."
              : "Automating chaos and scaling kludges since 2026."}
          </p>
        </div>

        {/* Ícones da Direita */}
        <div className="flex items-center gap-6">

          {/* Link do X (Twitter) */}
          <a
            href="https://x.com/xgh_ai"
            target="_blank"
            rel="noopener noreferrer"
            className="group flex items-center justify-center w-10 h-10 rounded-full border border-gray-800 bg-gray-900/50 text-gray-400 transition-all hover:border-neon-green hover:text-neon-green hover:shadow-[0_0_15px_rgba(57,255,20,0.3)]"
            title="Siga no X"
          >
            <FontAwesomeIcon icon={faTwitter} className="text-lg transition-transform group-hover:rotate-12" />
          </a>

        </div>
      </div>

      {/* ================================================================= */}
      {/* 🤖 POWERED BY SECTION: Gemini & Anthropic 🤖 */}
      {/* ================================================================= */}
      <div className="mt-12 pt-8 pb-4 border-t border-gray-900/50 flex flex-col items-center gap-4 relative z-10">
        <div
          className="flex flex-wrap justify-center gap-8 items-center cursor-pointer select-none"
          onClick={handlePoweredClick}
          title={lang === "pt" ? "Clique mais vezes..." : "Click more times..."}
        >

            {/* --- Google Gemini --- */}
            <a href="https://deepmind.google/technologies/gemini/" target="_blank" rel="noopener noreferrer"
               onClick={(e) => e.stopPropagation()}
               className="flex items-center gap-2 group opacity-60 hover:opacity-100 transition-all">
                <FontAwesomeIcon icon={faWandMagicSparkles} className="text-blue-400 group-hover:text-purple-400 transition-colors" />
                <span className="text-gray-400 font-bold tracking-tight text-xs group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-blue-400 group-hover:to-purple-500 transition-all">
                    Gemini
                </span>
            </a>

            <div className="h-3 w-[1px] bg-gray-800 hidden md:block"></div>

            {/* --- Anthropic --- */}
            <a href="https://www.anthropic.com/" target="_blank" rel="noopener noreferrer"
               onClick={(e) => e.stopPropagation()}
               className="flex items-center gap-2 group opacity-60 hover:opacity-100 transition-all">
                <FontAwesomeIcon icon={faBrain} className="text-orange-400/80 group-hover:text-orange-400 transition-colors" />
                <span className="text-gray-400 font-bold tracking-tight text-xs group-hover:text-white transition-all">
                    Anthropic
                </span>
            </a>
        </div>

        {/* Easter Egg Message */}
        {easterEgg && (
          <div className="animate-in fade-in slide-in-from-bottom-2 duration-300 bg-black/80 border border-neon-green/30 backdrop-blur-sm px-6 py-3 rounded-lg max-w-md text-center">
            <p className="text-neon-green text-xs font-mono leading-relaxed">
              {easterEgg}
            </p>
          </div>
        )}
      </div>
      {/* ================================================================= */}

      <div className="mt-6 text-center relative z-10">
        <p className="text-[10px] text-gray-700 font-mono uppercase tracking-widest">
          XGH-AI © 2026. {lang === "pt" ? "Desenvolvido com ódio e café." : "Developed with hate and coffee."}
        </p>
      </div>
    </footer>
  );
}
